language: java
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-latex-recommended
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install texlive-fonts-recommended
script:
  - make clean
  - make code
  - cd assignments
  - make docs
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: always
    on_failure: always
