language: java
script:
  - make clean
  - make code
  - cd assignments
  - make docs
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: always
    on_failure: always
